---
title: "Project 01 self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing
Wrote the entire abstract.
### Editing
Edited the abstract after writing the entire thing.

## Introduction
### Writing
Wrote a small section of the introduction on OTUs and ASVs.

### Editing
Briefly edited the introduction.

## Methods
### Editing
Briefly edited the methods section.

## Results
### Anaysis 
Did the vast majority of the analysis. 

### Figures
Ultimately generated all of the figures, based on the initial versions generated by Ryan Lou.

### Writing
Revised and wrote over such a substantial portion of Ryan Lou's work that it can't be called editing.

### Editing
Then edited it afterwards.

## Discussion
### Writing
Wrote half of the discussion, and substantially revised Sawera's work on the other half.

### Editing
Edited the discussion.