---
title: "Evidence_worksheet_02"
author: "Student Name (Student ID)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---
### Evidence Worksheet 02 “Life and the Evolution of Earth’s Atmosphere”
#### Learning objectives: 
Comment on the emergence of microbial life and the evolution of Earth systems.
    
#### Specific Questions:
* Indicate the key events in the evolution of Earth systems at each approximate moment in the time series. If times need to be adjusted or added to the timeline to fully account for the development of Earth systems, please do so. 

    + 4.6 billion years ago  
    Formation of the solar system and Earth. Currently, Earth is a large molten rock.
    + 4.5 billion years ago  
    Formation of the moon, giving Earth spin, tilt, day/night cycles, and seasons. CO2 buildup leads to beginning of greenhouse effect. 
    + 4.1 billion years ago  
    First evidence of life found in graphite within zircons
    + 3.8 billion years ago  
    Oceans, prokaryotic cells, Rubisco, stable sea chemistry, halted meteorite bombardment, methanogenesis
    + 3.75 billion years ago  
    Photosynthesis
    + 3.5 billion years ago  
    Cyanobacteria, microbial life on land
    + 2.9 billion years ago  
    Pongola glaciation, first global glaciation event
    + 2.7 billion years ago  
    Great oxidation event, red beds
    + 2.4 billion years ago  
    Huronian glaciation, first Snowball Earth
    + 2.1 billion years ago
    Appearance of eukaryotes, multicellular life, endosymbiosis
    + 1.3 billion years ago
    
    + 700 million years ago
    Cryogenian glaciation, second Snowball Earth
    + 550 million years ago
    Cambrian explosion, complex multicellular life, emergence of animals
    + 485 million years ago
    Land animals appear
    + 440 million years ago
    Ordovician-Silurian extinction events
    + 400 million years ago
    Land plants emerge, followed by a period of gigantism because of high oxygen atmosphere
    + 370 million years ago
    Late Devonian extinction(s)
    + 200,000 years ago
    First humans 

* Describe the dominant physical and chemical characteristics of Earth systems at the following waypoints:  

    + Hadean  
    Dry hot surface of planet (~500 C), 90 bar pressure on Earth's surface, CO2 sequestered in carbonate minerals such as limestone
    + Archean  
    Strong greenhouse gases predominate
    + Precambrian  
    
    + Proterozoic  
    Oxidation of the early atmosphere - microaerobic
    + Phanerozoic  
    Increased oxygenation of the atmosphere, mass extinction events from meteorite impacts
