---
title: "Problem Set_02"
author: "Student Name (Student ID)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---
### Problem set 02 “Microbial Engines”
#### Learning objectives: 
Discuss the role of microbial diversity and formation of coupled metabolism in driving global biogeochemical cycles.

#### Specific Questions:
* What are the primary geophysical and biogeochemical processes that create and sustain conditions for life on Earth? How do abiotic versus biotic processes vary with respect to matter and energy transformation and how are they interconnected?  
Geophysical processes - tectonics, atmospheric photochemical processes

Biogeochemical processes - H, C, N, O, S, and P fluxes

abiotic chemical processes tend to be based on acid/base reactions while biotic ones are based on redox. Reactions are nested, with abiotic processes providing e- acceptors that the biotic reactions use, as well as C, S, and P via tectonics, volcanism and weathering(?)

* Why is Earth’s redox state considered an emergent property?  
Emergent property of microbial life on earth

* How do reversible electron transfer reactions give rise to element and nutrient cycles at different ecological scales? What strategies do microbes use to overcome thermodynamic barriers to reversible electron flow?  
Synergistic multi-species assemblage of the overall pathway

* Using information provided in the text, describe how the nitrogen cycle partitions between different redox “niches” and microbial groups. Is there a relationship between the nitrogen cycle and climate change?   
  NH4 -> NO2 is a niche, NO2 -> NO3 is a niche; nitrification, typically involves CO2 fixation to organic matter
  NH4 + NO2 -> N2 (anammox)
  N2 -> NH4 reduction (N fixation)
  NO2 or NO3 -> NO -> N2O -> N2 (denitrification) and N2O can be released (greenhouse gas) 
  NO3 -> NO2 -> NH4 (Dissimilatory nitrate reduction to ammonium,  DNRA)

* What is the relationship between microbial diversity and metabolic diversity and how does this relate to the discovery of new protein families from microbial community genomes?  

* On what basis do the authors consider microbes the guardians of metabolism?  
