---
title: "Writing Assignment 01"
author: "Ryan Kaien Nah (28632115)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

### Module 01 Writing Assignment

**Prompt:** *"Microbial life can easily live without us; we, however, cannot survive without the global catalysis and environmental transformations it provides." Do you agree or disagree with this statement? Answer the question using specific reference to your reading, discussions and content from evidence worksheets and problem sets."*

  The first organisms on Earth were microbes, and as a result, many of the events dramatically impacting the Earth's development occurred as a direct consequence of microbial processes (1). Earth is only the way that it is today because of microbes, and they have sculpted the global biosphere in their image. Only in recent geological history with the appearance of humans and, more specifically, the emergence of human industrial technology, has the ecological balance of power been shifted away from microbial life (2-4). However, while humanity likely possesses or will someday possess the theoretical capacity to supplant the role of microbes in the biosphere, it is a foolish endeavour, as the earth was shaped by microbes for the sake of microbes, and a sizeable disruption in the way of things will likely have catastrophic effects across the global ecosystem, microbial or not. This is not to say that microbes are saint-like "guardians of metabolism", as Falkowski *et al.* put it (5); microbial competition and natural selection prove to be somewhat of a double-edged sword with dramatic consequences if the delicate balance between microbial cooperation and antagonism is perturbed. Additionally, humanity's ability to exploit microbial processes for human or global benefit as the slow march of technological progress continues will only increase, increasingly blurring the line between what is a distinctly microbial activity and what is human-driven, making such distinctions less and less relevant going forth. Consequently, while the prompt taken literally is true, its implication that microbes are controlling the direction of the global ecosystem is not. To invoke another set of metaphors for describing the complex relationship of humanity to the microbial realm, microbes are the biogeochemical "engines" of Spaceship Earth, of which humans are at the helm.  
  
  To call microbes intimately implicated in global biogeochemical cycling would be an understatement. Indeed, microbial processes underpin the global cycling of the 6 most important elements essential for life as we know it on Earth: Hydrogen, Carbon, Nitrogen, Oxygen, Phosphorus, and Sulfur (5-6). Even with the plethora of macroscopic multicellular terrestrial photosynthetic organisms that exist, unicellular marine microorganisms are responsible for the vast majority of the primary productivity occurring globally (6). Even non-microbial photosynthesis is arguably dependent on microbes on a different temporal scale, as chloroplasts were once a free-living photosynthetic organism that entered, perhaps unwillingly, into an endosymbiotic relationship with the common ancestor to all modern eukaryotic photosynthetic organisms (6). And speaking of plants, fixation of atmospheric dinitrogen to a form of nitrogen usable by plants such as nitrate within a given local ecosystem is often orchestrated by *Rhizobia* (7). Without these microbes present, the local ecosystem will very likely collapse without exogenous nitrate supplementation in the form of fertilizer. As powerful as this example is, however, it also demonstrates the fact that humans are also capable of manipulating a system to fit their needs if nature does not; modern agricultural processes are unable to rely on the comparatively limited amounts of fixed nitrogen these bacteria can produce, and must instead turn to industrial chemistry, namely the Haber-Bosch process, to produce sufficient fixed nitrogen for plant growth. Almost half of all the fixed nitrogen produced on Earth is anthropogenic (2), clearly illustrating that the role of humans in the biosphere is certainly not insignificant. Humans can take an otherwise biological process and scale it up industrially to levels which would be unfathomable for a microbial system. Additionally, this would take place on a human timescale rather than on a geological or an ecological one; where it took microbes millions if not billions of years in order to cause a substantial change in the atmosphere, humanity has only been around for several thousand years and already we can see the effects of humanity's existence, best exemplified by the global change in climate caused in no small part by greenhouse gas production as a result of human activity (3). Though this effect is certifiably negative, it highlights the extraordinary capacity of human actions to affect the biosphere on a timescale which is too rapid for microbes to even approach. Natural selection and competition do not enable microbial life to adapt and evolve as rapidly as human technological capabilities grow, meaning that while microbes are presently responsible for massive proportions of nutrient cycling, this may not necessarily remain to be the case in the future, and should any changes in the present equilibrium be required, microbes will more likely than not evolve too slowly to adapt to the new conditions, and a global catastrophe will occur should humanity not intervene.  
  
  Related to this idea, entirely ordinary microbial processes can often have overtly detrimental impacts due to excessive metabolic changes in response to environmental perturbations. Evidence for this is clearly visible from Earth's geological history, which is marred by several mass glaciations (8). Of particular importance for this discussion is the Huronian glaciation, which extended from about 2.4 billion years ago to 2.1 Ga, making it the oldest glaciation in Earth's history (8). Temporally, the Huronian glaciation closely followed the aptly-named Great Oxygenation event, which was the rapid appearance of substantial amounts of dioxygen gas in the atmosphere caused by the emergence of the evolutionary precursor to the modern-day *Cyanobacteria* (6, 8). As the surviving representatives are today, these early *Cyanobacteria* were photosynthetic, using the at-the-time untapped energy of the sun to power carbon fixation and thus their own growth, producing dioxygen as a by-product (6). However, much unlike it is today, that early atmosphere was largely anaerobic, dominated in large part by methane from methanogenesis (6). The rising levels of dioxygen would then react with methane, oxidizing it to CO~2~, greatly reducing its concentration and its potency as a greenhouse gas, leading to runaway planetary cooling due to photosynthesis and thus the eventual glaciation event (6). Additionally, dioxygen is toxic to obligate anaerobic organisms which were likely prolific at the time (6), implicating *Cyanobacteria* as the cause of one of the largest mass extinctions of Earth's history. While the oxygen-rich atmosphere created by the Great Oxidation Event was necessary for the eventual evolution of complex multicellular lifeforms such as humans, at the time, it was undoubtedly also the cause of a rapid catastrophic change in the biosphere, the effects of which humans feel to this day whenever any individual so much as takes a breath. Less dramatic examples of the detrimental effects of runaway microbial growth include algal blooms associated with eutrophication, which often leads to mass die-offs in the local area. As microbes are purely concerned about their own individual survival, a sudden evolutionary leap or a rapid change in growth conditions favouring one species over another can serve to cause rapid environmental damage and consequences, unable to be reversed by the slow pace of evolution. Indeed, natural selection is the cause of the damage; the dominant organism crowds out the rest, no matter how beneficial the others may be to the survival of the whole or the maintenance of the present equilibrium.  
  
  Additionally, the delineation between the microbial and the human realms is unnecessary if not borderline ridiculous. Since the first endosymbiotic events where once free-living *Cyanobacteria* or *Proteobacteria* were engulfed into a larger unicellular organism for mutual benefit (6), the lives of these burgeoning eukaryotes have always been crucially intertwined with the microbial world. Many symbiotic relationships connecting complex multicellular life to unicellular microorganisms have been identified just in the last two decades, some more akin to this foundational endosymbiosis than others. As alluded to earlier, *Rhizobia* species form nodules in the roots of some plant species and carry out biological nitrogen fixation to the benefit of the plant, losing its ability to be a free-living organism in the process (7). Certain types of squid such as the bobtail squid develop an organ deliberately to incentivize *Vibrio fischeri* colonization, a *Proteobacterium* which produces light to prevent the squid from casting a shadow and making it observable to predators (9). And of course, what discussion of the relationship of microorganisms with multicellular eukaryotic life would be complete without mentioning the resident human gut microbiota, where the number of microbial cells is about the same as the number of human cells in the human's very own body (10). Beyond this, the recent emergence of biotechnology, which is based entirely on manipulating and exploiting microbial processes for human industrial application, further blurs the line between the microbial and the human. If it is a microbe producing the biofuel in the human-created bioreactor under the conditions set deliberately by a human to get the microbe to best produce said biofuel, does that make it a microbial activity or a human one? Perhaps drawing a distinction between the two may have mattered early in Earth's history where complex inter-species relationships were in their infancy, but that certainly is no longer the case. Microbes are now intimately involved in most processes occurring on the earth whether they be metabolic or biogeochemical, and humanity is increasingly discovering ways of manipulating these same microbial processes for its own gain. Treating the two as separate entities can only be considered ignorant in today's day and age.  
  
  I have demonstrated thus far that microbes, while incredibly capable in very many regards, have their inequities due to being simple biological creatures driven solely by evolution and a drive for self-preservation. Though humanity is saddled with this same evolutionary baggage without the same inherent metabolic capabilities that microbes may possess, humans have the capacity for scientific innovation, vast industrial capabilities rivalling that of the microbial world, and the ability to deliberately choose their own direction independent of an evolutionary timescale, making them the main drivers of change in the biosphere. However, it is the horse that moves both itself and the rider atop it, and it is only on the metaphorical backs of the microbes around us that humanity can progress onwards. As such, I agree with the prompt taken literally, but would argue that its implication that the microbial world is responsible for setting the course of the global ecosystem is untrue. While microbes are the biogeochemical "engines" that power Spaceship Earth, it is humans that are at the helm.

#### References
1.  **Nisbet EG, Sleep NH.** 2003. The habitat and nature of early life. *Nature* 409:1083-1091. 
2.  **Canfield DE, Glazer AE, Falkowski PG.** 2010. The Evolution and Future of Earth's Nitrogen Cycle. *Science* 330:192-196. 
3.  **Rockström J, Steffen W, Noone K, Persson Å, Chapin FS, Lambin EF, Lenton TM, Scheffer M, Folke C, Schellnhuber HJ, Nykvist B, de Wit CA, Hughes T, van der Leeuw S, Rodhe H, Sörlin S, Snyder PK, Costanza R, Svedin U, Falkenmark M, Karlberg L, Corell RW, Fabry VJ, Hansen J, Walker B, Liverman D, Richardson K, Crutzen P, Foley JA.** 2009. A safe operating space for humanity. *Nature* 461:472-475. 
4.  **Schrag DP.** 2012. Geobiology of the Anthropocene, p 425-436. *In* Knoll AH, Canfield DE, Konhauser KO (ed), Fundamentals of Geobiology, 1st ed. Blackwell Publishing Ltd, Oxford, United Kingdom.
5.  **Falkowski PG, Fenchel T, Delong EF.** 2008. The Microbial Engines That Drive Earth's Biogeochemical Cycles. *Science* 320:1034-1039. 
6.  **Kasting JF, Siefert JL.** 2002. Life and the Evolution of Earth's Atmosphere. *Science* 296:1066-1068. 
7.  **Zahran HH.** 1999. *Rhizobium*-Legume Symbiosis and Nitrogen Fixation under Severe Conditions and in an Arid Climate. *Microbiol Mol Biol Rev* 63:968-989. 
8.  **Tang H, Chen Y.** 2013. Global glaciations and atmospheric change at ca. 2.3 Ga. *Geosci Front* 4:583-596. 
9.  **Ruby EG, Urbanowski M, Campbell J, Dunn A, Faini M, Gunsalus R, Lostroh P, Lupp C, McCann J, Millikan D, Schaefer A, Stabb E, Stevens A, Visick K, Whistler C, Greenberg EP.** 2005. Complete genome sequence of *Vibrio fischeri*: A symbiotic bacterium with pathogenic congeners. *Proc Natl Acad Sci U S A* 102:3004-3009. 
10. **Sender R, Fuchs S.** 2016. Are We Really Vastly Outnumbered? Revisiting the Ratio of Bacterial to Host Cells in Humans. *Cell* 164:337-340. 